# Generated by Django 5.2.9 on 2025-12-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Galleryimage',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='description',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='registrationnumber',
            field=models.CharField(default='none', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='members.html'),
        ),
    ]
