# Generated by Django 6.0 on 2025-12-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaapp', '0002_gallery_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('mpese_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaapp.member')),
            ],
        ),
    ]
