# Generated by Django 6.0 on 2025-12-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaapp', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='member-photos/'),
        ),
    ]
