# Generated by Django 6.0 on 2025-12-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramaapp', '0004_alter_member_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payments',
        ),
    ]
