# Generated by Django 6.0 on 2025-12-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramaapp', '0005_delete_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
